version: '2'
services:
    ng1-app:
        image: ng1
        external_links:
            - ng1-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ng1?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ng1-mysql:
        extends:
            file: mysql.yml
            service: ng1-mysql
